### ISSUE TITLE
Unable to reconstruct

### ISSUE THREAD

**Issue by shaidulberg** [Moors-Code/Eosinophils_scRNASeq#1]
Hello and thank you for publishing the code and making it available, it's extremely helpful.
While trying to reproduce your results, everything yielded the same output as you published, up until the 3.1 file (steadystate).
I struggle with reproducing your results there, I think it's related to what you wrote in a comment in line 27:
"#then run the analysis from line 6"
In the line after that you annotated 6 clusters, but I receive 4 (attached).
<img width="525" alt="000013" src="https://user-images.githubusercontent.com/97173459/209640452-032bc163-521f-452e-bde9-b86097b29dda.png">

Is there a chance you changed something there?

Thank you in advance!

**Comment by CocoBorrelli** [comment]
Hi, 

you are right, line 27 is wrong! I amended it and added some code to make it clearer! Now you first eliminate cluster 6 (differentiating neutrophils) and re-process. Then eliminate also some other contaminant clusters (mito high) to yield the final eosinophil_steadystate dataset! 

Sorry for the inconvenience and thanks for spotting the error!

Best, 
Coco

**Comment by shaidulberg** [comment]
Thank you very much! 
This fixed it.

**Comment by erkinacar5** [comment]
Please let us know if there are any further issues you face :)
