### ISSUE TITLE
Request for Sex Metadata for Single-Cell Dataset GSE182001

### ISSUE THREAD

**Issue by xqiu625** [Moors-Code/Eosinophils_scRNASeq#2]
Dear Moor Lab,

First, thank you for sharing the valuable single-cell dataset associated with the study “Active eosinophils regulate host defense and immune responses in colitis”. I am particularly interested in further analyzing the eosinophil populations within this dataset.

I am currently working on a project that requires identifying the sex of each cell from GSE182001, but I could not find the relevant metadata regarding the sex of the cells in the dataset. Could you kindly share this information if available?

Thank you for your time and support!

Xinru Qiu, PhD
xinru.qiu@ucr.edu

**Comment by erkinacar5** [comment]
Dear Xinru,

Unfortunately, the cell population is mixed. Male and female mice were pooled together so there is no telling which cell barcode belongs to which mouse, therefore, I cannot give any further information to help you with your research.

Sorry for the late reply and good luck on your further research!

Kind regards,
Erkin

**Comment by xqiu625** [comment]
Dear Erkin,

Thank you for your reply.
